### ISSUE TITLE
Flags increase width of rows

### ISSUE THREAD

**Issue by PonasKovas** [AlexBuz/mindsweeper#5]
![image](https://github.com/AlexBuz/mindsweeper/assets/25486263/1fb461fd-f010-4e23-98a0-f700b09b0745)
OS: Linux
Browser: Firefox 120.0.1

**Comment by Gurkenglas** [comment]
Can't reproduce in Debian in the same browser. Ctrl-S to save that HTML and upload it here?

**Comment by PonasKovas** [comment]
Saved HTML: https://pastebin.com/BwW7iZvq

**Comment by Gurkenglas** [comment]
Can't reproduce on Debian with your Firefox version or by opening that HTML. For me, ⚑ also looks different - mine looks like in https://github.com/AlexBuz/mindsweeper/issues/3#issuecomment-1858141698 . Maybe a different font? But none of https://www.fontspace.com/unicode/char/2691-black-flag looks like in your image...

**Comment by gtsiam** [comment]
Can you:
- Open the inspector (F12)
- Click the "pick element" option (top left)
- Pick a flag
- On the inspector on the right, choose the "Fonts" tab
- Which font is used?

Quick guess is that you're missing DejaVu Sans mono (which is the one used on my system), but it's gonna need a patch nonetheless.

**Comment by PonasKovas** [comment]
![image](https://github.com/AlexBuz/mindsweeper/assets/25486263/427aea3d-98cc-4648-9314-6413e03473e3)

**Comment by AlexBuz** [comment]
Thank you for the feedback! This should now be resolved.
