### ISSUE TITLE
Mobile friendly buttons

### ISSUE THREAD

**Issue by dlidstrom** [AlexBuz/mindsweeper#6]
Please make buttons mobile friendly. Perhaps under grid and full width?
Also, I find the timer to be stressful. It is difficult enough just to finish it. Otherwise I’m loving it, great job! I’m also intrigued about how you accomplished it.

**Comment by AlexBuz** [comment]
Thank you for the feedback! I added an option to disable the timer as of a few hours ago, and I'm planning on making it more mobile friendly soon.

**Comment by AlexBuz** [comment]
The whole interface is now more mobile friendly, including the buttons.
